In [47]:
import numpy as np 
import sklearn as sk 
import pandas as pd
import matplotlib as plt
import seaborn as sns 
import kagglehub
import random 
from sklearn.decomposition import PCA
from  sklearn.preprocessing import StandardScaler 
from sklearn_extra.cluster import KMedoids 
random_seed =18

In [19]:
df = pd.read_csv('Iris.csv')

print(df.head())
print(df.info())
df

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             150 non-null    int64
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB
None

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [ ]:
# removes no numeric columns 
X = df.iloc[: ,:-1]
X

      Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0      1            5.1           3.5            1.4           0.2
1      2            4.9           3.0            1.4           0.2
2      3            4.7           3.2            1.3           0.2
3      4            4.6           3.1            1.5           0.2
4      5            5.0           3.6            1.4           0.2
..   ...            ...           ...            ...           ...
145  146            6.7           3.0            5.2           2.3
146  147            6.3           2.5            5.0           1.9
147  148            6.5           3.0            5.2           2.0
148  149            6.2           3.4            5.4           2.3
149  150            5.9           3.0            5.1           1.8

[150 rows x 5 columns]

In [69]:
# normalize the data with StandardScaler 
scaler = StandardScaler()
X = scaler.fit_transform(X)
X.shape #shows (cols, rows)

(150, 5)

In [61]:
k =3 # there are three catagories of flowers

np.random.seed(random_seed)
medoid_indices = np.random.choice(X.shape[0], size=k, replace= False)
medoids = X[medoid_indices]

print("medoid indices: ",medoid_indices)
print("\nmediods: ", medoids)

medoid indices:  [81 92 80]

mediods:  [[ 0.15011441 -0.41600969 -1.51337539 -0.03336121 -0.26119297]
 [ 0.40415417 -0.05250608 -1.05056946  0.1372359   0.00175297]
 [ 0.12701988 -0.41600969 -1.51337539  0.02350449 -0.12972   ]]

In [72]:
def pairwise_distances(X,medoids):
    """
    Compute Elucidian distances between two set of points 
    A: shape (n_samples, n_features)
    B: shape (m_samples, n_features)
    returns: distances shape (n_samples, m_samples)
    """
    X_sq = np.sum(X**2, axis=1, keepdims=True)
    medoids_sq = np.sum(medoids**2, axis=1, keepdims=True)
    cross = X @ medoids.T # X * medoids.T
    print(cross.shape)
    dists = np.sqrt(X_sq + medoids_sq - (2*cross))
    return dists

In [75]:
distances = pairwise_distances(X, medoids)
labels = np.argmin(distances , axis=1)

(150, 3)

ValueError: operands could not be broadcast together with shapes (150,1) (3,1)